# Generated by Django 5.1.5 on 2025-02-04 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_date_of_birth_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted_users',
            field=models.ManyToManyField(blank=True, related_name='trusted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
